apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: https://prometheus.konnectkode.com
  basicAuth: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: $PASSWORD
  isDefault: true
  version: 1
  editable: true
